### ISSUE TITLE
No preservation of uppercase iwad file names

### ISSUE THREAD

**Issue by Sneethe** [zmnpl/twad#5]
It seems gzdoom has a fuzzy finder for IWADs. This means that if the iwad file name isn't exact it will load another IWAD. 

For an example if you have DOOM.WAD and DOOM2.WAD and load with gzdoom -iwad doom.wad. Gzdoom will open the DOOM2.WAD.

Looking at games.json . twad isn't preserving casing and it seems to exacerbate gzdoom somewhat. Editing the iwad filename to be correct again in the json returns normal iwad loading behavior for gzdoom.

**Comment by zmnpl** [comment]
Another good catch. Fixed this one I. Though you might need to go into the options (hit 'o') and save them again. Going into the options will make twad read the available IWADs from your file system again. This time it will preserve upper/lower case. + Then you probably need to edit/save the games which still have the incorrect spelling of an IWAD configured.
