### ISSUE TITLE
twad halts: GLIBC_2.32 not found

### ISSUE THREAD

**Issue by iainelder** [zmnpl/twad#8]
twad v0.20.3 doesn't start on my computer.

```console
$ twad
twad: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by twad)
twad: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by twad)
```

It looks like my version of GLIBC is too old.

```console
$ ldd --version | head -1
ldd (Ubuntu GLIBC 2.31-0ubuntu9.9) 2.31
$ lsb_release --description
Description:	Ubuntu 20.04.6 LTS
```

Can you make twad work on Ubuntu 20.04? Canonical supports it [until April 2025](https://wiki.ubuntu.com/Releases).

Otherwise, is there something I can do here other than compile it myself?

**Comment by zmnpl** [comment]
Hey, please check the latest release. I have compiled twad without cgo not (CGO_ENABLED=0). That should make it a statically linked binary and not require glibc anymore. Let me know if that worked for you.

**Comment by iainelder** [comment]
It works! It's beautiful. Thanks!

![image](https://github.com/zmnpl/twad/assets/5024311/d33634c2-89d4-44f0-a467-2785cbc4ebe4)
